#!/bin/sh
VERSION="1.2.109"
base_path=/usr/local/torrserver
pidfile=/var/run/torrserver.pid
#logfile=$base_path/torrserver.log
DAEMON=$base_path/bin/torrserver

service_start() {
 start-stop-daemon --start --quiet --background --make-pidfile --pidfile $pidfile \
                --exec $DAEMON -d $base_path/
}

service_stop() {
 start-stop-daemon --stop --pidfile $pidfile --exec $DAEMON
   RETVAL=$?
   [ $RETVAL -eq 0 ] && [ -e "$pidfile" ] && rm -f $pidfile
}

service_status() {
  start-stop-daemon --status -q -p $pidfile
  if [ -e $pidfile ]; then
     echo TorrServer running
  else
     echo TorrServer stopped
  fi
}

service_restart() {
  service_stop
  service_start
}

case $1 in
  start)
    service_start
    ;;
  stop)
    service_stop
    ;;
  status|enabled)
    service_status
    ;;
  restart)
    service_restart
    ;;
  *)
    echo "Usage: $(basename $0) {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0
